twig:
    file_name_pattern: '*.twig'
    globals:
        managed_locales: '%managed_locales%'
    path:
    '%kernel.project_dir%/assets/images/': images

when@test:
    twig:
        strict_variables: true
